# Anchors.

machine: &machine
  working_directory: ~/project

  docker:
    - image: circleci/node:10.15.0

      environment:
        SERVICE_GTM: ${SERVICE_GTM}

# Configuration.

version: 2.1

jobs:
  install:
    <<: *machine

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "yarn.lock" }}

      - store_artifacts:
          path: yarn-error.log

      - persist_to_workspace:
          root: ~/project
          paths: .

  test_static:
    <<: *machine

    steps:
      - attach_workspace:
          at: ~/project

      - run: ls -la

      - run:
          name: Execute static test
          command: yarn test:static

  test_unit:
    <<: *machine

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Execute unit test
          command: yarn test:unit

  build:
    <<: *machine

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Create build
          command: yarn build

      - persist_to_workspace:
          root: ~/project
          paths: .

  deploy:
    <<: *machine

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Push to GitHub Pages
          command: echo "yes" > yarn deploy

      - store_artifacts:
          path: yarn-error.log

workflows:
  version: 2.1

  process:
    jobs:
      - install:
          filters:
            branches:
              only: site

      - test_static:
          requires:
            - install

      - test_unit:
          requires:
            - install

      - build:
          requires:
            - test_static
            - test_unit

      - deploy:
          requires:
            - build
